package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

import java.util.Vector;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

public class mainScreenController {
	@FXML
	private TextField pregnancies;
	@FXML
	private TextField glucose;
	@FXML
	private TextField bp;
	@FXML
	private TextField skinthickness;
	@FXML
	private TextField insulin;
	@FXML
	private TextField bmi;
	@FXML
	private TextField dpf;
	@FXML
	private TextField age;
	@FXML
	private Button calculateButton; 
	@FXML
	private Label warningMessage; 
	@FXML
	private Label output; 

	// Event Listener on Button.onAction
	@FXML
	public void calculate(ActionEvent event) {
		// TODO Autogenerated
		if(!checkConditions()) {
			warningMessage.setText("Please make sure all fields are entered");
		}
		else {
			warningMessage.setText("");
			double p = sigmoid(Double.parseDouble(pregnancies.getText().toString()),1);;
			double g = sigmoid(Double.parseDouble(glucose.getText().toString()),1);;
			double b = sigmoid(Double.parseDouble(bp.getText().toString()),2);;
			double s = sigmoid(Double.parseDouble(skinthickness.getText().toString()),3);
			double i = sigmoid(Double.parseDouble(insulin.getText().toString()),4);
			double bm = sigmoid(Double.parseDouble(bmi.getText().toString()),5);
			double d = sigmoid(Double.parseDouble(dpf.getText().toString()),6);
			double a = sigmoid(Double.parseDouble(age.getText().toString()), 7);
			
			double avg = 100*((p + g + b + s + i + bm + d + a)/8);
			output.setText(avg + "%");
			
		}
	}
	// Event Listener on Button.onMouseEntered
	@FXML
	public void CalcButtonEntered(MouseEvent event) {
		
		//Changes style
		calculateButton.setStyle("-fx-background-color: #00008B;" + 
									"-fx-background-radius: 25");
		
	}
	// Event Listener on Button.onMouseExited
	@FXML
	public void CalcButtonExited(MouseEvent event) {
		// TODO Autogenerated
		// Changes style 
		calculateButton.setStyle("-fx-background-color: #4169E1;"+ 
									"-fx-background-radius: 25");
		
	}
	
	private double sigmoid(double x, int index) {

		return 1.0/(1.0 + Math.exp((-1 * (vector.coefs[index][0]*x + vector.coefs[index][1]))));		
	}
	
	private boolean checkConditions() {
		String p = pregnancies.getText().toString();
		String g = glucose.getText().toString();
		String b = bp.getText().toString();
		String s = skinthickness.getText().toString();
		String i = insulin.getText().toString();
		String bm = bmi.getText().toString();
		String d = dpf.getText().toString();
		String a = age.getText().toString();
		
		if(p.equals("") ||
				g.equals("") ||
				b.equals("") ||
				s.equals("") ||
				i.equals("") ||
				bm.equals("") ||
				d.equals("") ||
				a.equals("")) {
			return false;
		}
		else
			return true; 
	}
}
